### ISSUE TITLE
Error in folia 1.20.1

### ISSUE THREAD

**Issue by IamRymatics** [xF3d33/UltimateTeams#1]
[21:29:49] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/UltimateTeams-2.0.1.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/UltimateTeams-2.0.1.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'UltimateTeams v2.0.1' as it is not marked as supporting Folia!
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-"801cff1"]
	... 20 more

**Comment by xF3d33** [comment]
Hello, yeah i didn't mark the plugin as folia compatible in the plugin.yml..
