### ISSUE TITLE
[Feature Request] PostgreSQL as a storage option

### ISSUE THREAD

**Issue by NyaomiDEV** [xF3d33/UltimateTeams#24]
It would be nice to have Postgres as a storage option. Also, JDBC already supports it, so it should be easy to do.

**Comment by xF3d33** [comment]
Actually I thought about adding more storage methods, but according to bstats everyone is using SQLite... 
Are you asking to add this because you prefer postgreSQL on mysql?

**Comment by NyaomiDEV** [comment]
> Are you asking to add this because you prefer postgreSQL on mysql?

It's more of a "because I have PSQL set up already", but I don't really prefer anyone over the other. If anything I have more experience with MySQL.

**Comment by xF3d33** [comment]
with db5c4fbfa0b41a3416faf79e44355a1d6e0340d2 i actually added support for it, but i didn't even build it yet. if you want try it and let me know

**Comment by xF3d33** [comment]
https://modrinth.com/plugin/ultimate-teams/version/2.3

please try postgresql with this build and let me know if you encounter any error

**Comment by NyaomiDEV** [comment]
Sure thing, but I can't really do this in a short amount of time as I need to take an entire server down. I will hit you up soon enough, though.

**Comment by xF3d33** [comment]
You should try it on a test server before updating on production

**Comment by xF3d33** [comment]
I kinda recoded the whole database handler. H2 seems working fine, but I didn't try psql

**Comment by xF3d33** [comment]
Did you try it?

**Comment by NyaomiDEV** [comment]
> Did you try it?

Just now indeed.

```
[20:43:29 ERROR]: Error occurred while enabling UltimateTeams v2.3 (Is it up to date?)
java.lang.IllegalStateException: Failed to initialize PostgreSQL database connection
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:84) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.onEnable(UltimateTeams.java:109) ~[UltimateTeams-2.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:330) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at UltimateTeams-2.3.jar/net.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.3.jar:?]
        ... 13 more
Caused by: java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.database.PostgreSqlDatabase.initialize(PostgreSqlDatabase.java:52) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.lambda$onEnable$1(UltimateTeams.java:117) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/net.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.3.jar:?]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.database.PostgreSqlDatabase.initialize(PostgreSqlDatabase.java:52) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.lambda$onEnable$1(UltimateTeams.java:117) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/net.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[UltimateTeams-2.3.jar:?]
        at UltimateTeams-2.3.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.3.jar:?]
        ... 13 more
```

**Comment by xF3d33** [comment]
I think I know why. Can you send me a full startup log? You can use mcpaste from aternos

**Comment by NyaomiDEV** [comment]
It works in 2.4

**Comment by NyaomiDEV** [comment]
Got this error upon startup

```
[19:45:15 ERROR]: [UltimateTeams] Failed to fetch list of teams from table
org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 26
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[?:?]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[?:?]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.database.PostgreSqlDatabase.getAllTeams(PostgreSqlDatabase.java:118) ~[UltimateTeams-2.4.1.jar:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.utils.TeamStorageUtil.loadTeams(TeamStorageUtil.java:32) ~[UltimateTeams-2.4.1.jar:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.UltimateTeams.lambda$onEnable$4(UltimateTeams.java:128) ~[UltimateTeams-2.4.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[linearpaper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[19:45:15 INFO]: Loaded 0 teams!
```

Those others are upon logging in:
```
[19:45:22 INFO]: NyaomiPLAY joined the game
[19:45:22 INFO]: NyaomiPLAY[/<IP>] logged in with entity id 103 at ([world]-311.6575828298423, 74.0, -610.6093346585311)
[19:45:22 ERROR]: [UltimateTeams] Failed to get player from table
org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 15
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[?:?]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[?:?]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.database.PostgreSqlDatabase.getPlayer(PostgreSqlDatabase.java:188) ~[UltimateTeams-2.4.1.jar:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.utils.UsersStorageUtil.lambda$getPlayer$2(UsersStorageUtil.java:44) ~[UltimateTeams-2.4.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[linearpaper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[19:45:22 ERROR]: [UltimateTeams] Failed to create team in table
org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
  Position: 13
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[?:?]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[?:?]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:155) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.database.PostgreSqlDatabase.createPlayer(PostgreSqlDatabase.java:149) ~[UltimateTeams-2.4.1.jar:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.utils.UsersStorageUtil.lambda$getPlayer$1(UsersStorageUtil.java:49) ~[UltimateTeams-2.4.1.jar:?]
        at java.base/java.util.Optional.ifPresentOrElse(Unknown Source) ~[?:?]
        at UltimateTeams-2.4.1.jar/dev.xf3d3.ultimateteams.utils.UsersStorageUtil.lambda$getPlayer$2(UsersStorageUtil.java:44) ~[UltimateTeams-2.4.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[linearpaper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

```

**Comment by NyaomiDEV** [comment]
I did a PR to fix escaping, and you're welcome to merge it.

However, team data won't yet get retained and I don't know why.

**Comment by xF3d33** [comment]
> I did a PR to fix escaping, and you're welcome to merge it.
> 
> However, team data won't yet get retained and I don't know why.
> 
> The database update doesn't error out...

Wdym, the pr does fix it or are there still errors?

**Comment by NyaomiDEV** [comment]
> Wdym, the pr does fix it or are there still errors?

UT doesn't give any errors out anymore, but team data is not retained. If I set a team home and then I reboot the server, the home isn't retained. The only thing that is retained is the team existence.

I looked at the PSQL console and the JSON data field is never updated.

**Comment by xF3d33** [comment]
> > Wdym, the pr does fix it or are there still errors?
> 
> UT doesn't give any errors out anymore, but team data is not retained. If I set a team home and then I reboot the server, the home isn't retained. The only thing that is retained is the team existence.
> 
> I looked at the PSQL console and the JSON data field is never updated.
> 
> My PR made it so it would at least permit users to create teams.

Does it happen for like warps too?

**Comment by NyaomiDEV** [comment]
> Does it happen for like warps too?

It happens with warps, home, prefix. I am pretty sure that the update statement is missing something, however I don't really see any issues.

Do we need to put a semicolon at the end of it?

**Comment by xF3d33** [comment]
with a8736b3 everything should work, let me know
