### ISSUE TITLE
[BUG] GUI lib not working on MC 1.21

### ISSUE THREAD

**Issue by lackooka** [xF3d33/UltimateTeams#34]
**Describe the bug**
I write the command /team and it didnt do anything.

**To Reproduce**
1. Use 1.21 server
2. Use command: /team
3. Nothing happens into the game and error code in console

**Expected behavior**
Opens the gui

**Screenshots**
No screenshot

**Plugin version**
2.5

**Additional context**

[12:13:51 INFO]: lackooka issued server command: /team
[12:13:51 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
[12:13:51 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[12:13:51 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[12:13:51 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[12:13:51 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:13:51 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[12:13:51 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[12:13:51 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[12:13:51 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[12:13:51 WARN]:        at UltimateTeams-2.5-1725365623222.jar//dev.xf3d3.libraries.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:136)
[12:13:51 WARN]:        at UltimateTeams-2.5-1725365623222.jar//dev.xf3d3.libraries.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
[12:13:51 WARN]:        at UltimateTeams-2.5-1725365623222.jar//dev.xf3d3.ultimateteams.menuSystem.TeamListGUI.lambda$createGui$6(TeamListGUI.java:75)
[12:13:51 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[12:13:51 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:13:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:13:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:13:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:13:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[12:13:51 WARN]: [UltimateTeams] Plugin UltimateTeams v2.5 generated an exception while executing task 14059634
java.lang.ExceptionInInitializerError: null
        at UltimateTeams-2.5-1725365623222.jar/dev.xf3d3.ultimateteams.menuSystem.TeamListGUI.lambda$createGui$6(TeamListGUI.java:75) ~[UltimateTeams-2.5-1725365623222.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-DEV-4e55e26]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.jar:1.21-DEV-4e55e26]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: dev.xf3d3.libraries.triumphteam.gui.components.exception.GuiException: Could not retrieve displayName nor lore field for ItemBuilder.
        at UltimateTeams-2.5-1725365623222.jar/dev.xf3d3.libraries.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:86) ~[UltimateTeams-2.5-1725365623222.jar:?]
        ... 7 more

**Comment by xF3d33** [comment]
i think it is related to the GUI lib that is not updated to Minecraft 1.21. for now you should be able to use the plugin with the GUI system disabled, i'll updated the library asap

**Comment by Kruseified** [comment]
Can you get this updated sooner then later, with users using /team, its not great having consoled spammed with errors lol

**Comment by xF3d33** [comment]
> Can you get this updated sooner then later, with users using /team, its not great having consoled spammed with errors lol

I found a workaround, for now i'll push that. but as said in my previous comment you should be able to prevent the error by disabling the gui system

**Comment by Kruseified** [comment]
I did that and still received the error from my memory.

**Comment by xF3d33** [comment]
> I did that and still received the error from my memory.

can you write me on Discord (xF3d3) so i can send you a test build first?

**Comment by lackooka** [comment]
> > I did that and still received the error from my memory.
> 
> can you write me on Discord (xF3d3) so i can send you a test build first?

I send you a friend request (dlacoo)
