### ISSUE TITLE
[BUG] Menu GUI not working 

### ISSUE THREAD

**Issue by LeonBoettcher** [xF3d33/UltimateTeams#44]
**Describe the bug**
Using /team doesnt open up the GUI

**Plugin version**
UltimateTeams-2.5.jar

**Additional context**
Server LOG

[16:26:33 INFO]: DrunkenMueller issued server command: /team
[16:26:33 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
[16:26:33 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[16:26:33 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[16:26:33 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[16:26:33 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[16:26:33 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[16:26:33 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[16:26:33 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[16:26:33 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[16:26:33 WARN]:        at UltimateTeams-2.5.jar//dev.xf3d3.libraries.triumphteam.gui.components.util.VersionHelper.craftClass(VersionHelper.java:136)
[16:26:33 WARN]:        at UltimateTeams-2.5.jar//dev.xf3d3.libraries.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
[16:26:33 WARN]:        at UltimateTeams-2.5.jar//dev.xf3d3.ultimateteams.menuSystem.TeamListGUI.lambda$createGui$6(TeamListGUI.java:75)
[16:26:33 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[16:26:33 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:26:33 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:26:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:26:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:26:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[16:26:33 WARN]: [UltimateTeams] Plugin UltimateTeams v2.5 generated an exception while executing task 18032
java.lang.ExceptionInInitializerError: null
        at UltimateTeams-2.5.jar/dev.xf3d3.ultimateteams.menuSystem.TeamListGUI.lambda$createGui$6(TeamListGUI.java:75) ~[UltimateTeams-2.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: dev.xf3d3.libraries.triumphteam.gui.components.exception.GuiException: Could not retrieve displayName nor lore field for ItemBuilder.
        at UltimateTeams-2.5.jar/dev.xf3d3.libraries.triumphteam.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:86) ~[UltimateTeams-2.5.jar:?]
        ... 7 more

**Comment by xF3d33** [comment]
Hey, sorry for the delay. 
can you try this version?

https://modrinth.com/plugin/ultimate-teams/version/2.6-ALPHA
