### ISSUE TITLE
[BUG] Folia 1.21.1 not supporting

### ISSUE THREAD

**Issue by d0ddn** [xF3d33/UltimateTeams#45]
Ultimate Teams version: 2.5 and 2.6-Alpha
Console log:

```
[13:52:25 ERROR]: Error occurred while enabling UltimateTeams v2.6-ALPHA (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:524) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:228) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:210) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.libraries.aikar.commands.ACFBukkitScheduler.createLocaleTask(ACFBukkitScheduler.java:43) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.libraries.aikar.commands.BukkitCommandManager.<init>(BukkitCommandManager.java:131) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.libraries.aikar.commands.PaperCommandManager.<init>(PaperCommandManager.java:35) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.ultimateteams.UltimateTeams.onEnable(UltimateTeams.java:93) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:779) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:526) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:52:25 INFO]: [UltimateTeams] Disabling UltimateTeams v2.6-ALPHA
[13:52:25 INFO]: -------------------------------------------
[13:52:25 INFO]: UltimateTeams: Plugin by: xF3d3
[13:52:25 ERROR]: Error occurred while disabling UltimateTeams v2.6-ALPHA
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:524) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:341) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.libraries.morepaperlib.scheduling.BukkitSchedulerAsRegionalScheduler.cancelTasks(BukkitSchedulerAsRegionalScheduler.java:54) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.libraries.morepaperlib.scheduling.GracefulScheduling.cancelGlobalTasks(GracefulScheduling.java:162) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at UltimateTeams-2.6-ALPHA.jar/dev.xf3d3.ultimateteams.UltimateTeams.onDisable(UltimateTeams.java:247) ~[UltimateTeams-2.6-ALPHA.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:779) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:526) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:356) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by bovinespongiformflu** [comment]
Running into same issue, would love to have this plugin on folia, tried both stable and alpha, paperclip as well as mojang mapped jar's

**Comment by xF3d33** [comment]
i'm closing this issue as it is a duplicate of #55.
