### ISSUE TITLE
[BUG] /team setwarp error

### ISSUE THREAD

**Issue by Craiiger** [xF3d33/UltimateTeams#47]
/team setwarp <name> is coming back with an unexpected error.

11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] Exception in command: team setwarp xp
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] java.lang.NullPointerException: Cannot invoke "dev.xf3d3.ultimateteams.models.TeamPlayer.getMaxWarps(org.bukkit.entity.Player, int, boolean)" because "teamPlayer" is null
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.ultimateteams.commands.teamSubCommands.TeamSetWarpSubCommand.setWarpCommand(TeamSetWarpSubCommand.java:47)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.ultimateteams.commands.TeamCommand.onTeamSetWarpCommand(TeamCommand.java:78)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at java.base/java.lang.reflect.Method.invoke(Method.java:580)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.libraries.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.libraries.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:578)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.libraries.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.libraries.aikar.commands.RootCommand.execute(RootCommand.java:99)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at UltimateTeams-2.5.jar//dev.xf3d3.libraries.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:84)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.Commands.performCommand(Commands.java:350)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.Commands.performCommand(Commands.java:337)
11/26 9:43:45 AM [Error] [UltimateTeams] [ACF] at net.minecraft.commands.Commands.performCommand(Commands.java:332)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.TickTask.run(TickTask.java:18)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1586)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
11/26 9:43:45 AM [Error] [17:43:45 ERROR]: [UltimateTeams] [ACF] at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Craiiger** [comment]
Wanted to follow up on this thread.

**Comment by xF3d33** [comment]
Hi, sorry i've been busy studiyng in the last weeks. can you try if it works on a new mysql database? i think the plugin can't find the right information in your MySQL database.

**Comment by xF3d33** [comment]
Hi, i fixed this with the latest update. I'll close the issue, if you have any problem reopen it or create a new one
