### ISSUE TITLE
TeamDisbandSubCommand missing check to see if a team exist

### ISSUE THREAD

**Issue by dyzin** [xF3d33/UltimateTeams#8]
team disband i currently missing a check to see if the team actually exist.
If the doesn't exist bunch of error will show up instead

**Comment by Feryc-Projects** [comment]
[12:59:20 INFO]: I'm sorry, but there was an error performing this command.
[12:59:20 ERROR]: [UltimateTeams] [ACF] Exception in command: teamadmin disband team
[12:59:20 ERROR]: [UltimateTeams] [ACF] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.ultimateteams.commands.TeamAdmin.disbandSubcommand(TeamAdmin.java:73)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.libs.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.libs.acf.BaseCommand.execute(BaseCommand.java:513)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.libs.acf.RootCommand.execute(RootCommand.java:99)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at UltimateTeams-2.0.4.jar//dev.xf3d3.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:972)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:500)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:59:20 ERROR]: [UltimateTeams] [ACF]         at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Feryc-Projects** [comment]
also not respecting capital letters



teamadmin disband default
[13:06:54 INFO]: I'm sorry, but there was an error performing this command.
[13:06:54 ERROR]: [Feryc] [ACF] Exception in command: teamadmin disband default
[13:06:54 ERROR]: [Feryc] [ACF] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.ultimateteams.commands.TeamAdmin.disbandSubcommand(TeamAdmin.java:78)
[13:06:54 ERROR]: [Feryc] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:06:54 ERROR]: [Feryc] [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:06:54 ERROR]: [Feryc] [ACF]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:06:54 ERROR]: [Feryc] [ACF]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.libs.acf.BaseCommand.executeCommand(BaseCommand.java:578)
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.libs.acf.BaseCommand.execute(BaseCommand.java:513)
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.libs.acf.RootCommand.execute(RootCommand.java:99)
[13:06:54 ERROR]: [Feryc] [ACF]         at Feryc-dev-0.0.5.jar//dev.xf3d3.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[13:06:54 ERROR]: [Feryc] [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[13:06:54 ERROR]: [Feryc] [ACF]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1074)
[13:06:54 ERROR]: [Feryc] [ACF]         at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand(CraftServer.java:1059)
[13:06:54 ERROR]: [Feryc] [ACF]         at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:544)
[13:06:54 ERROR]: [Feryc] [ACF]         at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[13:06:54 ERROR]: [Feryc] [ACF]         at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1426)
[13:06:54 ERROR]: [Feryc] [ACF]         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1197)
[13:06:54 ERROR]: [Feryc] [ACF]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[13:06:54 ERROR]: [Feryc] [ACF]         at java.base/java.lang.Thread.run(Thread.java:840)
teamadmin disband Default
[13:06:59 INFO]: Team was disbanded!
